export enum PaymentDocumentType {
    WITHDRAWAL = 1,
    DEPOSIT = 2,
    CORRECTION_UP = 3,
    CORRECTION_DOWN = 4,
    LOYALTY_POINTS_CORRECTION_UP = 5,
    LOYALTY_POINTS_CORRECTION_DOWN = 6,
    BONUS_CORRECTION = 9,
    CASHBACK_CORRECTION = 10,
}
